/*
 * Created by SharpDevelop.
 * User: schraedl.g
 * Date: 5/6/2025
 * Time: 2:45 PM
 * 
 * To change this template use Tools | Options | Coding | Edit Standard Headers.
 */
using System;

namespace Prog366b {
    class Program {
        
        static int f(int x) { return (int)Math.Pow(x, 2) - x + 41; }
        
        // def is_prime(n: int, f: int) -> bool:
        static bool IsPrime(int n, int f) {
            // Trial Division Algorithm
            if (n <= 1) return false;
            if (n == 2 || f * f > n) return true;
            if (n % f == 0) return false;
            return IsPrime(n, f + 1);
        }
        
        static int FindSmallestFactor(int n) {
            for (int i = 2; i <= Math.Sqrt(n); i++)
                if (n % i == 0) return i;
            return n;
        }
        
        public static void Main(string[] args) {
            Console.WriteLine("The numbers generated by the formula x^2-x+41 are:");
            int x = 1;
            while (true) {
                int num = f(x);
                if (IsPrime(num, 2))
                    Console.WriteLine(num + "\tprime");
                else{
                    int factor = FindSmallestFactor(num);
                        Console.WriteLine(num + "\ttest fails/factor=" + factor);
                
                Console.ReadLine();
                return;
                }
                x++;
            }
            // for (int x = 1; ; x++)   
            
        }
    }
}